CREATE TABLE `id19088433_organ`.`chats`
 ( `id` INT NOT NULL AUTO_INCREMENT , 
 `user` LONGTEXT NOT NULL , `utmsmart` LONGTEXT NOT NULL ,
  `date` DATETIME NOT NULL , PRIMARY KEY (`id`)) 
  ENGINE = InnoDB; 